// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNzyNW15EqEmBbiV6MQSLWY9E_PRCmoU8',
    appId: '1:851934605056:web:d19a4d1f8c76cbe70e0de5',
    messagingSenderId: '851934605056',
    projectId: 'quizapp-a9e26',
    authDomain: 'quizapp-a9e26.firebaseapp.com',
    databaseURL:
        'https://quizapp-a9e26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizapp-a9e26.appspot.com',
    measurementId: 'G-LM855E1132',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiuYgyAVlJkypHS26NRM48dFlN2ytz1IM',
    appId: '1:851934605056:android:fa0c587942ceb7ba0e0de5',
    messagingSenderId: '851934605056',
    projectId: 'quizapp-a9e26',
    databaseURL:
        'https://quizapp-a9e26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizapp-a9e26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW8M9kKiz43LoF45zJg3EzfjPu7NICVzs',
    appId: '1:851934605056:ios:8a9ccbf650265f5a0e0de5',
    messagingSenderId: '851934605056',
    projectId: 'quizapp-a9e26',
    databaseURL:
        'https://quizapp-a9e26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizapp-a9e26.appspot.com',
    iosClientId:
        '851934605056-4l781nc6gn723dp0bjdja095pdj3iv7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW8M9kKiz43LoF45zJg3EzfjPu7NICVzs',
    appId: '1:851934605056:ios:8a9ccbf650265f5a0e0de5',
    messagingSenderId: '851934605056',
    projectId: 'quizapp-a9e26',
    databaseURL:
        'https://quizapp-a9e26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizapp-a9e26.appspot.com',
    iosClientId:
        '851934605056-4l781nc6gn723dp0bjdja095pdj3iv7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzerapp',
  );
}
